spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pantryfit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pantryfit}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pantryfit}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
